name: Manual iOS Build

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter Version'
        required: true
        default: '3.27.0'
        type: string
      xcode_version:
        description: 'Xcode Version'
        required: true
        default: '15.4'
        type: string

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ inputs.flutter_version }}

      - name: Get Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Build for iOS
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ inputs.xcode_version }}.app/Contents/Developer
          mkdir -p lib/l10n/generated
          flutter gen-l10n
          ls -R lib/l10n/generated || echo "L10n dir empty"
          dart run build_runner build --delete-conflicting-outputs
          
          # Build signed regular archive if possible, otherwise unsigned
          flutter build ios --release --no-codesign
          
          # Create Payload structure for IPA
          cd build/ios/Release-iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # Zip it up as unsinged IPA
          zip -r Anx-Reader-ios-manual-unsigned.zip Payload
          cp Anx-Reader-ios-manual-unsigned.zip Anx-Reader-ios-manual-unsigned.ipa
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            build/ios/Release-iphoneos/*.ipa
            build/ios/Release-iphoneos/*.zip
